Footnote pop-up and backreference links
Michael-F-Bryan/mdbook-epub pull request #123
Opened 2024-11-07 20:55 UTC by gambhiro

This adds an option to add backreference links at the end of footnote definitions, so that the user can return and continue reading the main body of the text.

The code is based on the [footnote-rewrite.rs](https://github.com/pulldown-cmark/pulldown-cmark/blob/master/pulldown-cmark/examples/footnote-rewrite.rs) example.

The pop-up footnote behaviour requires the use of `<aside>` tag and so EPUB 3 is required.

    [output.epub]
    epub-version = 3

I think most users would expect this behaviour and so I set the `footnote-backrefs` option to `true` by default, but it is only used when `epub-version = 3` is already selected.

On a Kindle Paperwhite, the footnote definition appears in a pop-up bottom window when the footnote reference number is tapped.

In KOReader on Remarkable 2 the footnote definition appears at the bottom of the screen.

The footnote definitions include a backreference link to jump back to the main body of the text.

This feature was also discussed at https://github.com/Michael-F-Bryan/mdbook-epub/issues/65

2025-01-03 18:23 UTC, blandger commented
Seems like there is new compiler version issue.

2025-01-04 05:22 UTC, gambhiro commented
@blandger It passes the checks now :+1:

2025-01-04 13:42 UTC, dieterplex commented
This PR deserves to have footnotes in markdown page of integration tests for users to know how to use. Maybe we can add another dummy to build ePub3 book and to verify it?

2025-01-04 14:31 UTC, dieterplex commented on src/generator.rs
> +    fn render_with_footnote_backrefs(&self, chapter_dir: &Path, ch: &Chapter) -> String {
I believe extracting closures at L304 & L385 to functions would improve readability. And extracting link filter logic to a function may reduce repetition.

2025-01-04 16:24 UTC, gambhiro commented on src/generator.rs
> +    fn render_with_footnote_backrefs(&self, chapter_dir: &Path, ch: &Chapter) -> String {
I managed to extract the one that was at L304 with the compiler messages helping me through it, but the other one gave me errors that I don't know how to deal with.

2025-01-04 20:00 UTC, gambhiro commented
> another dummy to build ePub3 book

I added a dummy with  `epub-version = 3` option and some tests to check that footnote backreference links are generated.

2025-01-05 10:41 UTC, blandger requested changes

2025-01-05 10:44 UTC, blandger commented
> This PR deserves to have footnotes in markdown page of integration tests...

Agree. 

I even think about several 'dummy book' examples/instances with different checking aspects. Like one book is for checking links between pages, another for local images check, third is for remote images check.

2025-01-05 12:18 UTC, gambhiro commented on src/config.rs
> +            footnote_backrefs: true,
OK, I updated the option and the README.

2025-01-05 12:40 UTC, blandger commented
Fixes were merged. Several libs are updated. Pls upgrade your branch by master.

2025-01-05 15:32 UTC, gambhiro commented
> Pls upgrade your branch by master

Seems ok now :+1:

2025-01-05 19:49 UTC, blandger requested changes

2025-01-05 19:49 UTC, blandger commented on src/generator.rs
> +            body.push_str(&self.render_with_footnote_backrefs(chapter_dir, ch));
Looks like we are repeating ourselves inside - `render_with_footnote_backrefs(.....)` making 
either flow for `epub_version == Some(3) && self.config.footnote_backrefs`
or alternative flow doing mostly the same functionality.

It would be good to have an 'optional step' in case conditions (epub_version + footnote_backrefs') for updating page content with all those functional (extracted into another component probably). Otherwise code becomes too long, compilcate and 'durty'... agree with @dieterplex 

Looks like `fn footnote_reference_event<'b>` can be extracted into separate module at least, something like 'footnote.rs'.

If you have complexities to refactor, I will do that after a merging PR into master. We need to do that before release new version.

2025-01-05 19:49 UTC, blandger commented on tests/dummy_epub3/book.toml
Could you pls rename that test book into something like - 'footnote_epub3_example'. We'll continue with several simple book examples in integration tests further.

2025-01-05 19:55 UTC, blandger commented
Overall I like that feature in the epub book, it looks very convenient and works fine (on my onyx ebook). Popup footnotes is what I really miss inside PDF books.

2025-01-05 20:13 UTC, gambhiro commented on tests/dummy_epub3/book.toml
This one was pretty low complexity :)

2025-01-05 20:20 UTC, gambhiro commented on src/generator.rs
> +            body.push_str(&self.render_with_footnote_backrefs(chapter_dir, ch));
It would be better if you or someone tackled the refactoring... I agree about the repeated function being bad style, but I couldn't resolve the compiler errors when I tried to refactor it. Rust is cool 😎 but sometimes it becomes a 4D-chess puzzle.

2025-01-06 08:54 UTC, merged